name: Push API to Main
on:
  push:
    branches: main
    paths:
      - "src/api/**"
      - "src/lambda-helpers.ts"
      - ".github/workflows/main_api.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_DEV_API_KEY: ${{ secrets.CLERK_DEV_API_KEY }}
  CLERK_INSTANCE_ID: ins_1oXZdmHyu1Lej3hCAgZjG8yJVV4
  CLOUDFRONT_ARN: ${{ secrets.CLOUDFRONT_ARN }}
  CONVERTKIT_API_TOKEN: ${{ secrets.CONVERTKIT_API_TOKEN }}
  DIAHOOK_SECRET: ${{ secrets.DIAHOOK_SECRET }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  LAMBDA_ROLE: ${{ secrets.LAMBDA_ROLE }}
  ROAM_API_TOKEN: ${{ secrets.ROAM_API_TOKEN }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_CHECKOUT_SECRET: ${{ secrets.STRIPE_CHECKOUT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: install
        run: npm install --force
      - name: Build
        run: npm run build:api
      - name: Upload
        run: |
          for filename in out/*.js; do
              LAMBDA=$(basename "$filename" .js)
              zip -jq $LAMBDA.zip ./out/$LAMBDA.js
              MODIFIED=$(aws lambda update-function-code --function-name "roam-js-extensions_${LAMBDA}" --publish --zip-file "fileb://${LAMBDA}.zip" --query "LastModified" --output text)  
              rm $LAMBDA.zip
              echo "Function $LAMBDA successfully updated at $MODIFIED"
          done
