name: Push Extensions to Main
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "src/components/**"
      - "src/entries/**"
      - "src/entry-helpers.ts"
      - "webpack.production.config.js"
      - "webpack.config.js"
      - ".github/workflows/main.yaml"
      - "package.json"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  ROAMJS_VERSION: production
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  MAPBOX_TOKEN: ${{ secrets.MAPBOX_TOKEN }}
  GIPHY_KEY: ${{ secrets.GIPHY_KEY }}
  API_URL: https://lambda.roamjs.com
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: install
        run: npm install --force
      - name: Build
        run: npm run build
      - name: Upload
        run: aws s3 sync build s3://roamjs.com
