name: Push Site to Main
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "components/**"
      - "public/**"
      - "pages/**"
      - "package.json"
      - ".github/workflows/main_index.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1
  NEXT_PUBLIC_REST_API_URL: "https://api.roamjs.com"
  NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.STRIPE_PUBLIC_KEY }}
  NEXT_PUBLIC_CLERK_FRONTEND_API: clerk.roamjs.com

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: Install
        run: npm install --force
      - name: Build
        run: npm run build:next
      - name: Upload
        run: |
          aws s3 sync out s3://roamjs.com
          for filename in $(find out -type f -name "*.html"); do
              HTML=$(echo $filename | cut -f 1 -d '.' | cut -d '/' -f 2-)
              aws s3 cp $filename s3://roamjs.com/$HTML --content-type "text/html"
          done
