name: Push Lambdas to Main
on:
  workflow_dispatch:
  push:
    branches: main
    paths:
      - "lambdas/**"
      - "webpack.lambda.config.js"
      - "tsconfig.json"
      - ".github/workflows/main_lambdas.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: npm install --force
      - name: Build
        run: npm run build:lambdas
      - name: Upload
        run: |
          for filename in out/*.js; do
              LAMBDA=$(basename "$filename" .js)
              zip -jq $LAMBDA.zip ./out/$LAMBDA.js
              MODIFIED=$(aws lambda update-function-code --function-name "roamjs-com_${LAMBDA}" --publish --zip-file "fileb://${LAMBDA}.zip" --query "LastModified" --output text)  
              rm $LAMBDA.zip
              echo "Function $LAMBDA successfully updated at $MODIFIED"
          done
