name: Push temp API to Master
on:
  workflow_dispatch:
  push:
    branches: master
    paths:
      - "lambdas/**"
      - "src/lambda-helpers.ts"
      - ".github/workflows/master_temp.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.LAMBDA_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.LAMBDA_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  CLERK_API_KEY: ${{ secrets.CLERK_API_KEY }}
  CLERK_DEV_API_KEY: ${{ secrets.CLERK_DEV_API_KEY }}
  CLERK_INSTANCE_ID: ins_1oXZdmHyu1Lej3hCAgZjG8yJVV4
  CLOUDFRONT_ARN: ${{ secrets.CLOUDFRONT_ARN }}
  CONVERTKIT_API_TOKEN: ${{ secrets.CONVERTKIT_API_TOKEN }}
  API_URL: https://api.roamjs.com
  DIAHOOK_SECRET: ${{ secrets.DIAHOOK_SECRET }}
  ENCRYPTION_SECRET: ${{ secrets.ENCRYPTION_SECRET }}
  DROPBOX_CLIENT_ID: ${{ secrets.DROPBOX_CLIENT_ID }}
  DROPBOX_CLIENT_SECRET: ${{ secrets.DROPBOX_CLIENT_SECRET }}
  FACEBOOK_CLIENT_ID: ${{ secrets.FACEBOOK_CLIENT_ID }}
  FACEBOOK_CLIENT_SECRET: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
  IFRAMELY_API_KEY: ${{ secrets.IFRAMELY_API_KEY }}
  LAMBDA_ROLE: ${{ secrets.LAMBDA_ROLE }}
  MIXPANEL_TOKEN: ${{ secrets.MIXPANEL_TOKEN }}
  SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
  SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_CHECKOUT_SECRET: ${{ secrets.STRIPE_CHECKOUT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.17.6
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.6
      - name: install
        run: npm install
      - name: Build
        run: npm run build:temp
